# Generated by Django 5.0.6 on 2024-06-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_alter_book_price_alter_book_rental_price_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rental_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
