# Generated by Django 5.0.6 on 2024-06-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_book_rental_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rental_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
