# Generated by Django 5.0.6 on 2024-06-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_alter_book_rental_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rental_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
